name: CT Pipeline

on:
  push:
    paths:
      - 'data/**'
      - 'src/train.py'
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrain Model & Update MLflow Registry
        run: |
          python src/train.py

      - name: Trigger CI Validation Pipeline
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run ci.yml --ref main
          